import type { Metadata } from "next";
import "./globals.css";
import PrivyProviders from "@/providers/PrivyProvider";
import VConsole from "@/components/VConsole";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <VConsole />
        <PrivyProviders>{children}</PrivyProviders>
      </body>
    </html>
  );
}
